#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

banner "Recover the Play upload key"

INPUT_AAB="app/build/outputs/bundle/release/app-release.aab"
OUTPUT_AAB="app/build/outputs/bundle/release/app-release-play-upload.aab"
KEYSTORE="/home/alex/secure-keys/mystuff-upload-2026.jks"
CERTIFICATE="/home/alex/secure-keys/mystuff-upload-2026.pem"
KEY_ALIAS="mystuff-upload-2026"
JAVA_HOME="${JAVA_HOME:-/opt/android-studio/jbr}"
KEYTOOL="$JAVA_HOME/bin/keytool"
JARSIGNER="$JAVA_HOME/bin/jarsigner"

stage "Generate a new upload key"
say "The old keystore is not changed. This creates a new classical RSA upload key at $KEYSTORE."
[[ -f "$INPUT_AAB" ]] || { warn "missing $INPUT_AAB; run ./gradlew :app:bundleRelease first"; exit 1; }
[[ ! -e "$KEYSTORE" ]] || { warn "$KEYSTORE already exists; choose a different recovery path"; exit 1; }
[[ ! -e "$CERTIFICATE" ]] || { warn "$CERTIFICATE already exists; choose a different recovery path"; exit 1; }
ask_secret STORE_PASSWORD "Choose a new upload keystore password (6+ characters):"
ask_secret KEY_PASSWORD "Choose a new upload key password (6+ characters):"
[[ ${#STORE_PASSWORD} -ge 6 && ${#KEY_PASSWORD} -ge 6 ]] || {
  warn "keystore and key passwords must each contain at least 6 characters"; exit 1;
}
confirm "Generate the new upload key now?" || { say "Cancelled; no key was created."; exit 0; }
umask 077
if ! printf '%s\n%s\n%s\n%s\n' "$STORE_PASSWORD" "$STORE_PASSWORD" "$KEY_PASSWORD" "$KEY_PASSWORD" | "$KEYTOOL" \
  -genkeypair -storetype JKS -keystore "$KEYSTORE" -alias "$KEY_ALIAS" \
  -keyalg RSA -keysize 2048 -validity 10000 \
  -dname "CN=MyStuff Upload, OU=MyStuff, O=Alex Zhidkov, L=Perth, ST=Western Australia, C=AU" \
  >/dev/null; then
  warn "could not generate the new upload key"; exit 1
fi
say "Created $KEYSTORE (private; keep it backed up securely)."

stage "Export the certificate for Play"
if ! printf '%s\n' "$STORE_PASSWORD" | "$KEYTOOL" -exportcert -rfc \
  -keystore "$KEYSTORE" -alias "$KEY_ALIAS" -file "$CERTIFICATE" \
  >/dev/null; then
  warn "could not export the upload certificate"; exit 1
fi
fingerprints=$("$KEYTOOL" -printcert -file "$CERTIFICATE" 2>/dev/null | awk -F': ' '/SHA1:|SHA256:/{print $1 ": " $2}')
[[ -n "$fingerprints" ]] || { warn "could not read the generated certificate"; exit 1; }
say "Upload this public certificate in the Play Console reset dialog: $CERTIFICATE"
printf '    %s\n' "$fingerprints"
pause "After the PEM is uploaded and Play enables Request, press Enter to sign the bundle"

stage "Sign and verify the replacement bundle"
say "The signed bundle will be written only to $OUTPUT_AAB."
confirm "Sign the release bundle with the new upload key?" || { say "Cancelled; no bundle was changed."; exit 0; }
mkdir -p "$(dirname "$OUTPUT_AAB")"
cp "$INPUT_AAB" "$OUTPUT_AAB"
if ! printf '%s\n%s\n' "$STORE_PASSWORD" "$KEY_PASSWORD" | "$JARSIGNER" \
  -keystore "$KEYSTORE" -sigalg SHA256withRSA -digestalg SHA-256 \
  "$OUTPUT_AAB" "$KEY_ALIAS" >/dev/null; then
  warn "jarsigner could not sign the bundle"; exit 1
fi
"$JARSIGNER" -verify "$OUTPUT_AAB" >/dev/null || { warn "the signed bundle failed verification"; exit 1; }
actual_upload_sha256=$("$KEYTOOL" -printcert -jarfile "$OUTPUT_AAB" 2>/dev/null | awk -F': ' '/SHA256:/{print $2; exit}')
say "Verified new upload SHA-256 certificate: ${actual_upload_sha256:-unknown}"
say "Signed bundle: $OUTPUT_AAB"
# ──────────────────────────────────────────────────────────────────────────

finish
